# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GithubPushNotificationsMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GithubPushNotificationsMobile
  pod 'DCTAuth', git: 'https://github.com/danielctull/DCTAuth.git'
  # pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
