def version_code
  commit_count = sh('git rev-list --count master')
  build_bump = File.read("#{__dir__}/buildBump")
  Integer(commit_count) + Integer(build_bump)
end

def feat_and_fixes_changelog
  changelog_from_git_commits
    .split("\n")
    .select { |string|
      string.index('feat:') || string.index('fix:') ||
        string.index('feat(') || string.index('fix(')
    }.join("\n")
end
