# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
skip_docs

def version_code
  commit_count = sh('git rev-list --count master')
  Integer(commit_count) + 84
end

platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :build do
    gym(scheme: 'PushForGithub')
  end

  lane :build_ci do
    match type: 'appstore'
    increment_build_number build_number: version_code
    gym(scheme: 'PushForGithub')
  end

  lane :beta_ci do
    next unless version_code > latest_testflight_build_number
    changelog = changelog_from_git_commits
    upload_to_testflight changelog: changelog
  end

  lane :build_and_beta do
    match type: 'appstore'
    increment_build_number build_number: version_code
    gym(scheme: 'PushForGithub')
    changelog = changelog_from_git_commits
    upload_to_testflight changelog: changelog
  end

  lane :deploy_ci do
    puts 'TODO'
  end
end
